#26 Unit test
listeph/ratemylandlord pull request #28
Opened 2021-11-28 22:14 UTC by Antsthebul

Created unit tests for all api URLs. Feel freed to ask if youo have any questions on the code or commecnts. I also updated the signal function models.py, since it was raising an error due to line #44. Float and Decimals cannot perform mathmatical equestions against each other. Also fixed ReviewFactory to inherit from LandlordFactory instead of trying to create a random int.

2021-11-29 12:36 UTC, listeph commented on rate_my_landlord/api/factory.py
> +    landlord = factory.SubFactory(LandlordFactory)
I think I want to keep this how it originally was because I'm trying to choose from existing Landlord objects to make the Review for in my [setup_test_data command](https://github.com/listeph/ratemylandlord/blob/729bd3307ebb3288df2d8173b10d41f57265bdae/rate_my_landlord/api/management/commands/setup_test_data.py#L24-L27). I think using SubFactory might just create a new Landlord object right?

2021-11-29 13:01 UTC, listeph requested changes
The unit tests look so good and clean, thank you @Antsthebul :) I just had a couple comments / questions about the other code changes

2021-11-29 15:12 UTC, Antsthebul commented on rate_my_landlord/api/tests/test_api.py
> +from rest_framework import serializers
That predictive import feature in VS code got me it seems. Sorry! I have removed these

2021-11-29 15:12 UTC, Antsthebul commented on rate_my_landlord/frontend/package-lock.json
> +  "lockfileVersion": 2,
I didnt install anything new but I think Im using a newer version of npm, so when I ran npm install it updated the lock version. Here's some info from their site. Im actually using vesrion 7.21.1

> 1: The lockfile version used by npm v5 and v6.
> 2: The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.

> Running npm install with npm 7 in a project with a v1 lockfile will replace that lockfile with the new v2 format. To avoid this, you can run npm install --no-save

2021-11-29 15:14 UTC, Antsthebul commented on rate_my_landlord/api/factory.py
> +    landlord = factory.SubFactory(LandlordFactory)
No problem. All fixed.

2021-11-30 00:22 UTC, listeph commented on rate_my_landlord/api/management/commands/setup_test_data.py
> +            ReviewFactory(landlord=landlord)
Is there a reason you aren't doing `ReviewFactory(landlord=Landlord.objects.order_by('?').first())`? I don't think landlord is defined in this scope, and I'd want different landlords for each review.

2021-11-30 00:22 UTC, listeph commented on rate_my_landlord/frontend/package-lock.json
> +  "lockfileVersion": 2,
Ohh I see thanks for researching! Looks good :)

2021-11-30 02:24 UTC, Antsthebul commented on rate_my_landlord/api/management/commands/setup_test_data.py
> +            ReviewFactory(landlord=landlord)
That does create different landlords for each review, but it's creating them sequentially, with the Landlord count == to the Review count. I apologize I didnt fully underant what you were ting to do. I see that you were trying to make 150 Reviews also. The issue wtih `Landlord.objects.order_by('?').first()` is that your querying the database everytime this runs in the *for-loop * (50 times to be exact) and then trying to randomize each query. Django mentions that, that specific call  could potentially be expensive. Although a cool one! So ive updated the code to quickly create 150 reviews, with a randomly selected, already reated, Landlord for each review.

2021-12-02 08:34 UTC, listeph approved these changes
Looks good! Thanks so much for adding these unit tests

2021-12-02 08:34 UTC, listeph commented on rate_my_landlord/api/management/commands/setup_test_data.py
> +            ReviewFactory(landlord=landlord)
Oh oops my bad I didn't see that you deleted the `for _ in range(NUM_REVIEWS):` line too so I was confused and that's why I said `landlord` isn't defined in this scope. Yes what you say makes sense, and thank you for sharing about `bulk_create`!

2021-12-02 08:41 UTC, merged